
FROM oven/bun:1-alpine AS builder
WORKDIR /app

# Copy lockfile and package.json first for caching
COPY bun.lock package.json ./
RUN bun install --frozen-lockfile


COPY . .

RUN bun run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
# Copy the built files from the 'builder' stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80 for the browser
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
